### PR TITLE
Cleaning up some files in /root

### PR DESCRIPTION
**Pull request by joshsamuelson**
I'm going to move all of the post-build cleanup scripts to this manifest so that we're less dependent on bash scripts.

### CODE REVIEW

**Comment by joshsamuelson** [comment]
FIXES TRAINVM-152

**Comment by klynton** [comment]
When will this run? I know I've used those log files to troubleshoot more than one build issue.

**Comment by joshsamuelson** [comment]
It runs right before the final VM is packaged.  So they are preserved on the base image, but when we turn that into a shippable VM they'll be blown away.  The jenkins based build relies on VM pooler base images which are managed by the product team, so I don't think we need to keep these files around in the final image either way.

**Comment by klynton** [comment]
:+1:

**Pull request merged**
